.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.Dd Jan 29, 2023
.\" Please adjust this date whenever revising the manpage.
.Dt XPLUGD 1 URM
.Os
.Sh NAME
.Nm xplugd
.Nd an X input/output plug in/out helper
.Sh SYNOPSIS
.Nm
.Op Fl hnpsv
.Op Fl l Ar LEVEL
.Ar [FILE]
.Sh DESCRIPTION
.Nm
is a daemon that executes a script on X input and RandR changes, i.e.,
if a keyboard, mouse or monitor is plugged in or unplugged.  Useful if
you want to run
.Xr xrandr 1 ,
.Xr xinput 1 ,
or
.Xr setxkbmap 1
when docking or undocking a laptop.
.Pp
By default
.Nm
forks to the background and exits when the X server exits.
.Sh OPTIONS
.Pp
.Bl -tag -width Ds
.It Fl h
Print help and exit
.It Fl l Ar LVL
Set log level for syslog messages, where
.Ar LVL
is one of: none, err, info,
.Ar notice ,
debug.  Use
.Fl l Ar debug
to enable debug messages.  Default:
.Ar notice
.It Fl n
Run in foreground, do not detach from calling terminal and fork to background
.It Fl p
Probe currently connected outputs and output EDID info
.It Fl s
Use syslog, even if running in foreground, default w/o
.Fl n
.It Fl v
Show version information and exit
.El
.Pp
The optional
.Pa FILE
argument defaults to
.Pa $XDG_CONFIG_HOME/xplugrc ,
with fallbacks to
.Pa ~/.config/xplugrc
and
.Pa ~/.xplugrc .
The file is called as a script on plug events with the following
arguments:
.Bl -tag -width Ds -offset indent
.It $1 = Ar TYPE
One of
.Ar display | keyboard | pointer
.It $2 = Ar DEVICE
Usually HDMI3, LVDS1, VGA1, or an
.Xr xinput 1
device number.
.It $3 = Ar STATUS
One of
.Ar connected | disconnected | unknown
.It $4 = Ar DESCRIPTION
An optional description enclosed in double quotes, e.g., keyboard
(manufacturer and) model name, or if EDID data is available from a
connected display, the monitor model
.El
.Sh EXAMPLE
Here is an example of how to use
.Nm :
.Bd -literal -offset indent
xplugd
.Ed
.Pp
When
.Nm
starts it looks for the file
.Pa ~/.config/xplugrc ,
which may look something like this:
.Bd -literal -offset indent
#!/bin/sh

type=$1
device=$2
status=$3
desc=$4

case "$type,$device,$status,$desc" in
  display,DVI-0,connected,*)
        xrandr --output DVI-0 --auto --right-of LVDS
        ;;
  display,VGA-0,connected,*)
        xrandr --output VGA-0 --auto --left-of LVDS
        ;;
  pointer,*,connected,"SynPS/2 Synaptics TouchPad")
        xinput set-prop $device 'Synaptics Off' 1
        ;;
  keyboard,*connected,*)
        setxkbmap -option ctrl:nocaps
        ;;
esac
.Ed
.Sh FILES
.Bl -tag -width $XDG_CONFIG_HOME/xplugrc -compact
.It Pa $XDG_CONFIG_HOME/xplugrc
Primary path
.It Pa ~/.config/xplugrc
Secondary path
.It Pa ~/.xplugrc
Fallback path, for compat with earlier releases
.El
.Sh SEE ALSO
.Bl -tag -compact
.It Aq http://bitbucket.org/portix/srandrd
.It Aq https://bitbucket.org/andrew_shadura/inputplug
.It Aq https://github.com/troglobit/xplugd
.El
.Sh AUTHORS
.Nm
was created by Joachim Wiberg in 2016 for use with window managers like
.Xr awesome 1
and
.Xr i3 1 .
It would however not exist if not for the hard work of Stefan Bolte with
.Nm srandrd
and Andrew Shadura with
.Nm inputplug .
