.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.Dd Apr 24, 2013
.\" Please adjust this date whenever revising the manpage.
.Dt SRANDRD 1
.Os
.Sh NAME
.Nm srandrd
.Nd A simple randr daemon
.Sh SYNOPSIS
.Nm
.Op Fl hnvV
.Ar COMMAND
.Sh DESCRIPTION
.Nm
is a tool that executes a command on xrandr output change events, i.e.,
if a monitor is plugged or unplugged.  By default srandrd forks to the
background and exits when the X server exits.
.Sh OPTIONS
.Pp
.Bl -tag -width Ds
.It Fl h
.RS 4
Print help and exit
.It Fl n
Run in foreground, do not detach from calling terminal and fork to background
.It Fl v
Enable verbose messages.  Useful for debugging in the foreground
.It Fl V
Show version information and exit
.El
.Pp
The environment variable
.Ar SRANDRD_ACTION
is passed to the command with the following value:
.Bd -literal -offset indent
DISPLAYNAME [connected|disconnected|unknown]
.Ed
.Sh EXAMPLE
Here is an example of how to use
.Nm :
.Bd -literal -offset indent
srandrd /path/to/my-script.sh
.Ed
.Pp
Where
.Ar /path/to/my-script.sh
could look something like this:
.Bd -literal -offset indent
#!/bin/sh

case "$SRANDRD_ACTION" in
  "DVI-0 connected")
	xrandr --output DVI-0 --auto --right-of LVDS
	;;
  "VGA-0 connected")
	xrandr --output VGA-0 --auto --left-of LVDS
	;;
esac
.Ed
.Sh RESOURCES
.Bl -tag -compact
.It bitbucket: Aq http://bitbucket.org/portix/srandrd
.It GitHub: Aq https://github.com/troglobit/srandard
.El
.Sh AUTHOR
.An Stefan Bolte Aq mailto:portix@gmx.net
