.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.Dd Mar 29, 2016
.\" Please adjust this date whenever revising the manpage.
.Dt XPLUGD 1 URM
.Os
.Sh NAME
.Nm xplugd
.Nd an X input/output plug in/out helper
.Sh SYNOPSIS
.Nm
.Op Fl hnv
.Op Fl l Ar LEVEL
.Ar SCRIPT
.Sh DESCRIPTION
.Nm
is a daemon that executes a script on X input and RandR changes, i.e.,
if a keyboard, mouse or monitor is plugged in or unplugged.  Useful if
you want to run
.Xr xrandr 1 ,
.Xr xinput 1 ,
or
.Xr setxkbmap 1
when docking or undocking a laptop.
.Pp
By default
.Nm
forks to the background and exits when the X server exits.
.Sh OPTIONS
.Pp
.Bl -tag -width Ds
.It Fl h
Print help and exit
.It Fl l Ar LVL
Set log level for syslog messages, where
.Ar LVL
is one of: none, err, info,
.Ar notice ,
debug.  Use
.Fl l Ar debug
to enable debug messages
.It Fl n
Run in foreground, do not detach from calling terminal and fork to background
.It Fl s
Use syslog, even if running in foreground, default w/o
.Fl n
.It Fl v
Show version information and exit
.El
.Pp
The
.Ar SCRIPT
is called with the following arguments:
.Bl -tag -width Ds -offset indent
.It $1 = Ar TYPE
One of
.Ar display | keyboard | pointer
.It $2 = Ar DEVICE
Usually HDMI3, LVDS1, VGA1, or an
.Xr xinput 1
device number.
.It $3 = Ar STATUS
One of
.Ar connected | disconnected | unknown
.It $4 = Ar DESCRIPTION
An optional description enclosed in double qoutes, only used for
.Xr xinput 1
devices, like the keyboard manufacturer and model name.
.El
.Sh EXAMPLE
Here is an example of how to use
.Nm :
.Bd -literal -offset indent
xplugd my-script.sh
.Ed
.Pp
Where
.Ar my-script.sh
could look something like this:
.Bd -literal -offset indent
#!/bin/sh

type=$1
device=$2
status=$3
desc=$4

case "$type,$device,$status,$desc" in
  display,DVI-0,connected,*)
        xrandr --output DVI-0 --auto --right-of LVDS
        ;;
  display,VGA-0,connected,*)
        xrandr --output VGA-0 --auto --left-of LVDS
        ;;
  pointer,*,connected,"SynPS/2 Synaptics TouchPad")
        xinput set-prop $device 'Synaptics Off' 1
        ;;
  keyboard,*connected,*)
        setxkbmap -option ctrl:nocaps
        ;;
esac
.Ed
.Sh SEE ALSO
.Aq http://bitbucket.org/portix/srandrd
.Aq https://bitbucket.org/andrew_shadura/inputplug
.Aq https://github.com/troglobit/xplugd
.Sh AUTHORS
.Nm
was created by Joachim Nilsson in 2016 for use with window managers like
.Xr awesome 1 .
It would however not exist if not for the hard work of Stefan Bolte with
.Nm srandrd
and Andrew Shadura with
.Nm inputplug .
