.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.Dd Mar 29, 2016
.\" Please adjust this date whenever revising the manpage.
.Dt XPLUGD 1 URM
.Os
.Sh NAME
.Nm xplugd
.Nd monitor plug/unplug helper
.Sh SYNOPSIS
.Nm
.Op Fl hnvV
.Ar SCRIPT
.Sh DESCRIPTION
.Nm
is a tool that executes a script on xrandr output change events, i.e.,
if a monitor is plugged or unplugged.  By default xplugd forks to the
background and exits when the X server exits.
.Sh OPTIONS
.Pp
.Bl -tag -width Ds
.It Fl h
.RS 4
Print help and exit
.It Fl n
Run in foreground, do not detach from calling terminal and fork to background
.It Fl v
Enable verbose messages.  Useful for debugging in the foreground
.It Fl V
Show version information and exit
.El
.Pp
The environment variable
.Ar XPLUG_EVENT
passed to the script has the following syntax:
.Bd -literal -offset indent
DISPLAYNAME [connected|disconnected|unknown]
.Ed
.Pp
E.g.
.Bd -literal -offset indent
HDMI3 connected
.Ed
.Sh EXAMPLE
Here is an example of how to use
.Nm :
.Bd -literal -offset indent
xplugd /path/to/my-script.sh
.Ed
.Pp
Where
.Ar /path/to/my-script.sh
could look something like this:
.Bd -literal -offset indent
#!/bin/sh

case "$XPLUG_EVENT" in
  "DVI-0 connected")
	xrandr --output DVI-0 --auto --right-of LVDS
	;;
  "VGA-0 connected")
	xrandr --output VGA-0 --auto --left-of LVDS
	;;
esac
.Ed
.Sh AUTHORS
Stefan Bolte is the original author of
.Nm
under its former guise as
.Nm srandrd ,
.Aq http://bitbucket.org/portix/srandrd .
In 2016 An Joachim Nilsson forked and renamed the project for further
development at
.Aq https://github.com/troglobit/xplugd .
